### ISSUE TITLE
[BUG] The package filters online results even if isFilteredOnline is set to true, causing some results loaded via onFind to get filtered and removed.

### ISSUE THREAD

**Issue by NamanShergill** [salim-lachdhaf/searchable_dropdown#116]
### How to reproduce
For example, if one were to search "Delh" via [the Nominatim API](https://nominatim.org/release-docs/latest/api/Search/) in the `onFind` param and return the results, one of the results would be "Valz-sous-Châteauneuf, Issoire, Puy-de-Dôme, Auvergne-Rhône-Alpes, Metropolitan France, 63580, France". This result would get filtered, even if the flag `isFilteredOnline` is set to `true`.

### What is causing this
https://github.com/salim-lachdhaf/searchable_dropdown/blob/70fa71937a4d0c7b9b958d00fb96c46685b2bf91/lib/src/selectDialog.dart#L225
```dart  
List<T> applyFilter(String filter) {
      return _items.where((i) {
        if (widget.filterFn != null)
          return (widget.filterFn(i, filter));
        else if (i.toString().toLowerCase().contains(filter.toLowerCase()))
          return true;
        else if (widget.itemAsString != null) {
          return (widget.itemAsString(i))
                  ?.toLowerCase()
                  ?.contains(filter.toLowerCase()) ??
              false;
        }
        return false;
      }).toList();
    }
```

As you can see, it filters the result in ` else if (i.toString().toLowerCase().contains(filter.toLowerCase()))`, because technically "delh" is not in the string  "Valz-sous-Châteauneuf, Issoire, Puy-de-Dôme, Auvergne-Rhône-Alpes, Metropolitan France, 63580, France", causing it to get filtered out.

### Expected Behavior
Considering `isFilteredOnline` is set to true, the dropdown should show *all* results by default, considering the flag itself implies the filtering is already done online by the API. 

### How it might be fixed
The applyFilter function should not be used for the results given by the API in this scenario (unless the user specifically passes `filterFn`).

**Comment by salim-lachdhaf** [comment]
fixed in v0.4.9

**Comment by NamanShergill** [comment]
> fixed in v0.4.9

I just tested this version, the bug is still happening.

**Comment by NamanShergill** [comment]
@salim-lachdhaf Could this issue please be re-opened, the bug is still occurring.

**Comment by salim-lachdhaf** [comment]
fixed in v0.5.0
