### ISSUE TITLE
setState() called after dispose()

### ISSUE THREAD

**Issue by patachi** [salim-lachdhaf/searchable_dropdown#340]
### Error : 

════════ Exception caught by scheduler library ════════
The following assertion was thrown during a scheduler callback:
setState() called after dispose(): FormFieldState<List<Roles>>#f1469(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to **check the "mounted" property of this object before calling setState()** to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack
#0      State.setState.<anonymous closure> ................... package:flutter/…/widgets/framework.dart:1052
#1      State.setState ................... package:flutter/…/widgets/framework.dart:1087
#2      FormFieldState.didChange ................... package:flutter/…/widgets/form.dart:409
#3      DropdownSearchState._formFieldMultiSelection.<anonymous closure>.<anonymous closure> ................... package:dropdown_search/**dropdown_search.dart:575**
#4      SchedulerBinding._invokeFrameCallback ................... package:flutter/…/scheduler/binding.dart:1145
#5      SchedulerBinding.handleDrawFrame ................... package:flutter/…/scheduler/binding.dart:1090
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> ................... package:flutter/…/scheduler/binding.dart:863

(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
════════════════════════════════════════
`
`

**Comment by vasilich6107** [comment]
@patachi 
It would be good to attach reproduction sample

**Comment by salim-lachdhaf** [comment]
fixed in the last version.

**Comment by DanyGalarneau** [comment]
Hello I still have the issue with the 5.0.2 version

ERROR:

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
setState() called after dispose(): FormFieldState<Vault?>#f8e39(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1073:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1108:6)
#2      FormFieldState.didChange (package:flutter/src/widgets/form.dart:409:5)
#3      DropdownSearchState._formFieldSingleSelection.<anonymous closure>.<anonymous closure> (package:dropdown_search/dropdown_search.dart:382:19)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1091:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)

**Comment by DanyGalarneau** [comment]
It happens when there is a setState in the onChanged function

```onChanged: (vault) async {
                        if(mounted) {
                          setState(() {
                            isLoading = true;
                          });
                        }
                        // Do something
                        if(mounted) {
                          setState(() {
                            isLoading = false;
                          });
                        }
                      }

**Comment by zachary22321** [comment]
I got this too.

I use Riverpod, but it's the same thing a chance of state in the onchangemethod
