### ISSUE TITLE
DropdownSearch value resets whole changing focus

### ISSUE THREAD

**Issue by Ayan4044** [salim-lachdhaf/searchable_dropdown#51]
I was trying to use the Widget in a row and also in a dynamic widget, the problem is that as change the focus to other input widgets the value resets. In case you use **selecteditem** attribute then it resets to the initial value. 

`Row(
 children: [
Flexible(
          flex: 1,
          child: Padding(
            padding: EdgeInsets.only(left: 5),
            child: TextFormField(
              controller: _descriptionController,
              onChanged: (v) =>
              _UpdateFormState.descriotiondata[widget.index] = v,
              validator: (v) {
                if (v
                    .trim()
                    .isEmpty) return 'Please enter Study Description';
                return null;
              },
              style: TextStyle(color: Colors.blue),
              decoration: InputDecoration(
                counterText: '',
                filled: true,
                fillColor: Color(0xFFF5F5F5),
                labelText: "Description",
                labelStyle: TextStyle(color: Color(0xFF45B4FF)),
                focusedBorder: OutlineInputBorder(
                  borderSide: BorderSide(color: Colors.blueAccent, width: 1.0),
                ),
                enabledBorder: OutlineInputBorder(
                  borderSide: BorderSide(color: Colors.blueGrey, width: 1.0),
                ),
              ),
            ),
          ), /* TextFormField(
            controller: _descriptionController,
            onChanged: (v) {
              _UpdateFormState.descriotiondata[widget.index] = v;
            },
            decoration: InputDecoration(
                hintText: 'Study Description'
            ),
            validator: (v){
              if(v.trim().isEmpty) return 'Please enter Study Description';
              return null;
            },
          ),*/
        ),
        SizedBox(width: 10),
        Flexible(
          flex: 2,
          child: DropdownSearch<StudyName>(
            mode: Mode.BOTTOM_SHEET,
            isFilteredOnline: true,
            showClearButton: true,
            showSearchBox: true,
            items: studyNamemodel,
            itemAsString: (StudyName u) => u.studyName,
            onChanged: (StudyName data) {
              print(data.studyName);
              _UpdateFormState.dropdowndata[widget.index] = data.studyName;
              //FocusScope.of(context).nextFocus();
            },
            maxHeight: 300,
            onFind: (String filter) => getData(filter),
            label: "Study Name",
          ),
        ),
      ],
    );`

For further reference, I had already posted this on [stackoverflow ](https://stackoverflow.com/questions/64471581/flutter-dropdownsearch-value-resets-on-changing-focus-to-other-widgets
)here is the link

**Comment by salim-lachdhaf** [comment]
check v 0.4.6, this should be fixed.

**Comment by Ayan4044** [comment]
Okay will try out

**Comment by ZafarAhmad74** [comment]
I tried but this problem still there secondly If you save data and restart the app how to update the widget to that state

**Comment by ZafarAhmad74** [comment]
Let me know if I want to reopen the issue or create a new one

**Comment by salim-lachdhaf** [comment]
Check my anwser in stackoverflow, let me know if it works for you.
And take a look to this it could help
https://github.com/salim-lachdhaf/searchable_dropdown/issues/56

I'm waiting for your feedback

**Comment by ZafarAhmad74** [comment]
Thank you very much for such a quick reply and I apologize that I didn't look at the link for Stackoverflow and commented, however, I found it later the both of my questions are answered. 
Thanks again for helping.
Regards,Zafar
    On Thursday, November 5, 2020, 01:08:37 AM GMT+5, Salim Lachdhaf <notifications@github.com> wrote:  
 
 


Check my anwser in stackoverflow, let me know if it works for you.
And take a look to this it could help
#56

I'm waiting for your feedback

**Comment by ZafarAhmad74** [comment]
Thank you very much for such a quick reply and I apologize that I didn't look at the link for Stackoverflow and commented, however, I found it later the both of my questions are answered. 

Thanks again for helping.

Regards,
Zafar

**Comment by Ayan4044** [comment]
Hi I have tested it, its working thanks for the fix
